# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booking.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"\x08\n\x06\x45mpty3\"\x1b\n\x08Message3\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x18\n\x06UserID\x12\x0e\n\x06userid\x18\x01 \x01(\t\"A\n\x10\x42ookingsByUserID\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x1d\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\x0e.MoviesByDate3\"-\n\rMoviesByDate3\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"D\n\x13\x42ookingDataToCreate\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0f\n\x07movieid\x18\x03 \x01(\t2\xc7\x01\n\x07\x42ooking\x12\x1c\n\x04Home\x12\x07.Empty3\x1a\t.Message3\"\x00\x12-\n\x0bGetBookings\x12\x07.Empty3\x1a\x11.BookingsByUserID\"\x00\x30\x01\x12\x33\n\x13GetBookingsByUserID\x12\x07.UserID\x1a\x11.BookingsByUserID\"\x00\x12:\n\rCreateBooking\x12\x14.BookingDataToCreate\x1a\x11.BookingsByUserID\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY3._serialized_start=17
  _EMPTY3._serialized_end=25
  _MESSAGE3._serialized_start=27
  _MESSAGE3._serialized_end=54
  _USERID._serialized_start=56
  _USERID._serialized_end=80
  _BOOKINGSBYUSERID._serialized_start=82
  _BOOKINGSBYUSERID._serialized_end=147
  _MOVIESBYDATE3._serialized_start=149
  _MOVIESBYDATE3._serialized_end=194
  _BOOKINGDATATOCREATE._serialized_start=196
  _BOOKINGDATATOCREATE._serialized_end=264
  _BOOKING._serialized_start=267
  _BOOKING._serialized_end=466
# @@protoc_insertion_point(module_scope)
