# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import booking_pb2 as booking__pb2


class BookingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Home = channel.unary_unary(
                '/Booking/Home',
                request_serializer=booking__pb2.Empty3.SerializeToString,
                response_deserializer=booking__pb2.Message3.FromString,
                )
        self.GetBookings = channel.unary_stream(
                '/Booking/GetBookings',
                request_serializer=booking__pb2.Empty3.SerializeToString,
                response_deserializer=booking__pb2.BookingsByUserID.FromString,
                )
        self.GetBookingsByUserID = channel.unary_unary(
                '/Booking/GetBookingsByUserID',
                request_serializer=booking__pb2.UserID.SerializeToString,
                response_deserializer=booking__pb2.BookingsByUserID.FromString,
                )
        self.CreateBooking = channel.unary_unary(
                '/Booking/CreateBooking',
                request_serializer=booking__pb2.BookingDataToCreate.SerializeToString,
                response_deserializer=booking__pb2.BookingsByUserID.FromString,
                )


class BookingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Home(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBookings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBookingsByUserID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Home': grpc.unary_unary_rpc_method_handler(
                    servicer.Home,
                    request_deserializer=booking__pb2.Empty3.FromString,
                    response_serializer=booking__pb2.Message3.SerializeToString,
            ),
            'GetBookings': grpc.unary_stream_rpc_method_handler(
                    servicer.GetBookings,
                    request_deserializer=booking__pb2.Empty3.FromString,
                    response_serializer=booking__pb2.BookingsByUserID.SerializeToString,
            ),
            'GetBookingsByUserID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookingsByUserID,
                    request_deserializer=booking__pb2.UserID.FromString,
                    response_serializer=booking__pb2.BookingsByUserID.SerializeToString,
            ),
            'CreateBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBooking,
                    request_deserializer=booking__pb2.BookingDataToCreate.FromString,
                    response_serializer=booking__pb2.BookingsByUserID.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Booking', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Booking(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Home(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Booking/Home',
            booking__pb2.Empty3.SerializeToString,
            booking__pb2.Message3.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Booking/GetBookings',
            booking__pb2.Empty3.SerializeToString,
            booking__pb2.BookingsByUserID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBookingsByUserID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Booking/GetBookingsByUserID',
            booking__pb2.UserID.SerializeToString,
            booking__pb2.BookingsByUserID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Booking/CreateBooking',
            booking__pb2.BookingDataToCreate.SerializeToString,
            booking__pb2.BookingsByUserID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
