# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: showtime.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshowtime.proto\"\x1b\n\x08Message2\x12\x0f\n\x07message\x18\x01 \x01(\t\",\n\x0cMoviesByDate\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"+\n\x08Schedule\x12\x1f\n\x08schedule\x18\x01 \x03(\x0b\x32\r.MoviesByDate\"\x14\n\x04\x44\x61te\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"\x08\n\x06\x45mpty22u\n\x08Showtime\x12\x1c\n\x04Home\x12\x07.Empty2\x1a\t.Message2\"\x00\x12 \n\x08GetTimes\x12\x07.Empty2\x1a\t.Schedule\"\x00\x12)\n\x0fGetMoviesByDate\x12\x05.Date\x1a\r.MoviesByDate\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'showtime_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE2._serialized_start=18
  _MESSAGE2._serialized_end=45
  _MOVIESBYDATE._serialized_start=47
  _MOVIESBYDATE._serialized_end=91
  _SCHEDULE._serialized_start=93
  _SCHEDULE._serialized_end=136
  _DATE._serialized_start=138
  _DATE._serialized_end=158
  _EMPTY2._serialized_start=160
  _EMPTY2._serialized_end=168
  _SHOWTIME._serialized_start=170
  _SHOWTIME._serialized_end=287
# @@protoc_insertion_point(module_scope)
